### ISSUE TITLE
Improve option/mode checks

### ISSUE THREAD

**Issue by PHLAK** [PHLAK/Twine#1]
Replace instances of `in_array` with `defined`.

https://github.com/PHLAK/Twine/blob/master/src/Traits/Convinience.php#L20-L24

Example:

```php
$base64Types = [Config::BASE64_ENCODE, Config::BASE64_DECODE];

if (! in_array($mode, $base64Types, true)) {
    throw new InvalidConfigOptionException('$mode must be one of ' . implode(', ', $base64Types));
}
```

```php
if (! defined($mode)) {
     throw new InvalidConfigOptionException('Invalid $mode specified'));
}
```

**Comment by PHLAK** [comment]
https://github.com/eloquent/enumeration

**Comment by peter279k** [comment]
Hi @PHLAK, thank you for your reply.
Can you tell more details about this?
It seems that you want to use the ```eloquent/enumeration``` to fix this issue?
