### ISSUE TITLE
Please add encrypt and decrypt methods also

### ISSUE THREAD

**Issue by tzsk** [PHLAK/Twine#4]
Hey, Awesome package. This is a feature request.

Would love to see these methods:

**Normal:** `$string->encrypt($key)` and `$string->decrypt($key)`

And optional Parameter for URL Safe: which is just `urlencoded`

**URL Safe:** `$string->encrypt($key, Twine\Config\Encryption::SAFE)` and just `$string->decrypt($key)`
> Because it will be automatically `urldecoded` in the Request.

**Alias:** `$string->encryptSafe($key)` and just `$string->decrypt($key)`

Thank you.

**Comment by PHLAK** [comment]
Twine already has the [`crypt`](https://github.com/PHLAK/Twine#crypt) method that I believe would fill the need you express for `encrypt()`. As for making the resulting hash URL safe maybe we should add a new method so you can do something like this:

    $string->crypt('some_random_salt')->urlEncode();

**Comment by PHLAK** [comment]
Also, maybe we should implement the [`password_hash()`](https://secure.php.net/manual/en/function.password-hash.php) and [`password_verify()`](https://secure.php.net/manual/en/function.password-verify.php) functions as well.

**Comment by PHLAK** [comment]
Looked at this again just now and I see what you want. You want a reversible `encrypt()` method, not a one-way hash.

**Comment by tzsk** [comment]
Yes. That's right. I was thinking of reversible Encryption. Not hashing. 

Also chaining urlencode is also great.
