### ISSUE TITLE
Question: Multi-Byte/Unicode/UTF-8 String Support

### ISSUE THREAD

**Issue by broberts-dev** [PHLAK/Twine#41]
Chris,

I reviewed the README.md and docs, but didn't find any mentions (not to say they're not there) of multi-byte string handling or support. Maybe multi-byte string support is just one of the baked-in benefits of Twine?

When I reviewed some of the the code (master branch), it appeared in many, if not most, cases Twine utilizes PHP's multi-byte string functions available through its MBSTRING extension (https://www.php.net/manual/en/book.mbstring.php).

So, I wanted to ask. What's the goal or intent of the project with respect to multi-byte strings? For example, Does Twine intend to provide operations that are "multi-byte string" compatible/safe?

Thanks in advance for any response. Please forgive me if I overlooked this information in README.md or the docs. This seems like an appropriate means of asking the question, particularly since others may have similar questions and the issue and its correspondence would be there for posterity.

Regards,

Ben R

**Comment by broberts-dev** [comment]
And, related, given the reliance on MBSTRING extension functions, should composer.json require ext-mbstring?

**Comment by PHLAK** [comment]
> What's the goal or intent of the project with respect to multi-byte strings? For example, Does Twine intend to provide operations that are "multi-byte string" compatible/safe?

Yes, Twine aims to be fully multi-byte compatible. That being said, if you discover any issues please report them.

> ... should composer.json require ext-mbstring

Yeah, probably.

**Comment by broberts-dev** [comment]
Very minor change, but I submitted a pull request, if you'd like to incorporate it that way.
