### ISSUE TITLE
Small typo ;-)

### ISSUE THREAD

**Issue by mikeerickson** [PHLAK/Twine#5]
You have a typo in a few places of class names.  You have used `convinience` where I believe you meant `convenience`

http://www.dictionary.com/browse/convenience?s=t

Example

https://github.com/PHLAK/Twine/blob/master/src/Traits/Convinience.php

**Comment by PHLAK** [comment]
Doh! This isn't the first time I've misspelled "convenience" either... will fix.

**Comment by mikeerickson** [comment]
@phlak I know the feeling, I spelt it wrong many times in my life.  Nice package btw
